import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

import {
  Bot,
  RefreshCw,
  ShieldCheck,
} from "lucide-react";

import SecurityStatus from "./SecurityStatus";
import InsightChips from "./InsightChips";

interface Props {

  summary: string;

  score: number;

  lastUpdated: Date | null;

  refreshing: boolean;

  onRefresh: () => void;

}

export default function AISummaryCard({

  summary,

  score,

  lastUpdated,

  refreshing,

  onRefresh,

}: Props) {

  return (

    <div
      className="
      rounded-2xl
      overflow-hidden
      bg-gradient-to-br
      from-slate-900
      via-slate-800
      to-slate-900
      border
      border-slate-700
      shadow-xl
      "
    >

      {/* Header */}

      <div className="flex items-center justify-between px-8 py-6 border-b border-slate-700">

        <div className="flex items-center gap-4">

          <div
            className="
            h-14
            w-14
            rounded-2xl
            bg-cyan-500
            flex
            items-center
            justify-center
            shadow-lg
            "
          >

            <Bot
              size={30}
              className="text-white"
            />

          </div>

          <div>

            <h2 className="text-2xl font-bold text-white">

              🛡️ AI Security Overview

            </h2>

            <p className="text-slate-300">

              Executive Security Brief generated by CyberGPT

            </p>

          </div>

        </div>

        <button
          disabled={refreshing}
          onClick={onRefresh}
          className="
          flex
          items-center
          gap-2
          rounded-xl
          bg-cyan-600
          hover:bg-cyan-500
          disabled:opacity-60
          px-5
          py-3
          transition
          text-white
          "
        >

          <RefreshCw
            size={18}
            className={
              refreshing
                ? "animate-spin"
                : ""
            }
          />

          {

            refreshing

              ? "Refreshing..."

              : "Refresh"

          }

        </button>

      </div>

      {/* Body */}

      <div className="p-8">

        <SecurityStatus
          score={score}
        />

        <InsightChips
          score={score}
        />

        <div
          className="
          rounded-xl
          border
          border-slate-700
          bg-slate-950/40
          p-6
          "
        >

          <div className="flex items-center gap-3 mb-5">

            <ShieldCheck
              className="text-cyan-400"
              size={22}
            />

            <h3 className="text-lg font-semibold text-white">

              AI Generated Executive Summary

            </h3>

          </div>

          <div
            className="
            text-slate-200

            [&_h1]:text-white
            [&_h2]:text-white
            [&_h3]:text-white
            [&_h4]:text-white

            [&_p]:text-slate-200
            [&_p]:leading-8
            [&_p]:mb-4

            [&_strong]:text-cyan-300

            [&_ul]:list-disc
            [&_ul]:ml-6

            [&_ol]:list-decimal
            [&_ol]:ml-6

            [&_li]:mb-2
            [&_li]:text-slate-200

            [&_code]:text-cyan-300

            [&_pre]:bg-slate-900
            [&_pre]:rounded-lg
            [&_pre]:p-4
            "
          >

            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
            >

              {summary}

            </ReactMarkdown>

          </div>

        </div>

      </div>

      {/* Footer */}

      <div
        className="
        flex
        justify-between
        items-center
        px-8
        py-5
        border-t
        border-slate-700
        "
      >

        <div className="text-green-400 font-medium">

          ✓ Powered by CyberGPT

        </div>

        <div className="text-slate-400 text-sm">

          {

            lastUpdated

              ? `Updated at ${lastUpdated.toLocaleTimeString([], {
                  hour: "2-digit",
                  minute: "2-digit",
                })}`

              : "Not Updated"

          }

        </div>

      </div>

    </div>

  );

}