import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

import {
  Bot,
  Sparkles,
  RefreshCw,
  ShieldCheck,
} from "lucide-react";

interface Props {

  summary: string;

  lastUpdated: Date |null;

  refreshing: boolean;

  onRefresh: () => void;

}

export default function AISummaryCard({

  summary,

  lastUpdated,

  refreshing,

  onRefresh,

}: Props) {

  return (

    <div
      className="
      rounded-2xl
      bg-gradient-to-br
      from-slate-900
      via-slate-800
      to-slate-900
      shadow-xl
      border
      border-slate-700
      overflow-hidden
      "
    >

      {/* Header */}

      <div className="flex items-center justify-between px-8 py-6 border-b border-slate-700">

        <div className="flex items-center gap-5">

          <div className="w-14 h-14 rounded-2xl bg-cyan-500 flex items-center justify-center">

            <Bot
              size={28}
              className="text-white"
            />

          </div>

          <div>

            <h2 className="text-2xl font-bold text-white">

              🛡️ AI Security Overview

            </h2>

            <p className="text-slate-300">

              Executive Security Brief generated by CyberGPT

            </p>

          </div>

        </div>

        <button

          disabled={refreshing}

          onClick={onRefresh}

          className="flex items-center gap-2 rounded-xl bg-cyan-600 hover:bg-cyan-500 disabled:opacity-60 px-5 py-3 transition"

        >

          <RefreshCw

            size={18}

            className={refreshing ? "animate-spin" : ""}

          />

          {refreshing

            ? "Refreshing..."

            : "Refresh"}

        </button>

      </div>

      {/* Badge */}

      <div className="px-8 pt-6">

        <div className="inline-flex items-center gap-2 rounded-full bg-cyan-500/20 px-4 py-2 text-cyan-300">

          <Sparkles size={18}/>

          AI Generated Executive Summary

        </div>

      </div>

      {/* Markdown */}

      <div
        className="
        px-8
        py-8

        text-slate-200

        [&_h1]:text-white
        [&_h2]:text-white
        [&_h3]:text-white
        [&_h4]:text-white

        [&_strong]:text-cyan-300

        [&_p]:text-slate-200
        [&_p]:leading-8

        [&_li]:text-slate-200
        [&_li]:mb-2

        [&_ul]:list-disc
        [&_ul]:ml-6

        [&_ol]:list-decimal
        [&_ol]:ml-6

        [&_code]:text-cyan-300

        [&_pre]:bg-slate-950
        [&_pre]:rounded-xl
        [&_pre]:p-4
        "
      >

        <ReactMarkdown
          remarkPlugins={[remarkGfm]}
        >

          {summary}

        </ReactMarkdown>

      </div>

      {/* Footer */}

      <div className="flex items-center justify-between px-8 py-5 border-t border-slate-700">

        <div className="flex items-center gap-2 text-green-400">

          <ShieldCheck size={18}/>

          Powered by CyberGPT

        </div>

        <div className="text-slate-400 text-sm">

          {lastUpdated
            ? `Updated at ${lastUpdated.toLocaleTimeString()}`
            : "Not updated"}

        </div>

      </div>

    </div>

  );

}